name: CI

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install
        run: pip install --editable ".[dev]"
      - name: Ruff
        run: |
          python -m ruff check .
          python -m ruff format --check .
      - name: Mypy
        run: python -m mypy src
      - name: Unit tests
        run: python -m pytest tests/unit
